### ISSUE TITLE
Fantastic work!

### ISSUE THREAD

**Issue by Ataraksia** [GaspardCulis/elevenlabs-unleashed#1]
So I just recently started a project where I had a need for a TTS model, and after testing pretty much all the major ones I concluded, as many others in the community have as well it seems, that ElevenLabs is indeed the best of the bunch at the moment, and so like many others I excitedly signed up only to be immediately greeted by the roundhouse kick to the face that is the outrageously expensive pricing.  Sheesh, I thought I knew a thing or two or about overpriced AI models with GPT-4's rates... nuh-uh man, ElevenLabs out here making OpenAI's pricing look downright reasonable by comparison. I was on the verge of going with a crappier option to avoid breaking the bank only to randomly stumble upon this repo, which at first glance I admit I assumed to be a scam of some kind haha.  But after going through the readme and then going over the code realized just how brilliant your work on this was.  While the idea behind it as you mentioned is a fairly simple one overall, it's the implementation that's the hard part, not the idea.  Heck I myself had the same idea pop into my head of taking advantage of the free plan with multiple accounts, but pretty quickly dismissed it as the massive pain the ass I realized it would be.  But you didn't just have the idea, you also successfully implemented it and even went so far as to make it publicly available; that is the very definition of going above and beyond right there.  

I can happily report that your script has been working nearly flawlessly for me so far.  The only slight hiccup being from what looks to be the recent changes you made in transitioning from the ELUAccountManager class to the UnleashedTTS class, resulting in part of your usage guide no longer being relevant.  With that said, it was easy enough to understand what was going on after a few minutes of looking through the code thanks to your documentation.  In my limited testing thus far I haven't faced any issues with having my access restricted at all either, which I attribute to the VPN I use automatically rotating IP addresses every five minutes. With a little luck, ElevenLabs won't change their account creation process in a way that prevents this method from working any time soon, although if they do I shall try my best to assist you in getting it working again and report back here if I am successful.  

Alright, well I think that's all I had to say.  Really all of this is just my way of saying thanks in the most unnecessarily long winded way possible, and with that task now completed, I shall take my leave.  Good day, sir!  

Oh, and obviously this isn't really an issue report, so feel free to close it after you're done reading it.

**Comment by GaspardCulis** [comment]
Man thanks a lot for this positive feedback :+1: , means a lot to me knowing that my public code helps others, it keeps me motivated. If you have any suggestions/issues go ahead, you can even submit pull requests that I'll be happy to review and merge.
Good luck on your project, and if one day you plan to release it on github, let me know, I'm very interested on what people can do with a bit of my code, especially AI stuff.

Godspeed !

**Comment by LegendaryFxN** [comment]
@GaspardCulis Any tutorials by any chance?

**Comment by GaspardCulis** [comment]
Other than in the README, no, maybe you can take inspiration from my [jarvis](https://github.com/GaspardCulis/jarvis) project where I used this lib.
