### ISSUE TITLE
Can you add - custom adding voice from url?

### ISSUE THREAD

**Issue by CroSSer23** [GaspardCulis/elevenlabs-unleashed#10]
Can you add - custom adding voice from url?

**Comment by CroSSer23** [comment]
I don't want to use simple voices, I want to use custom ones. I just need to follow the link and add a voice after registering an account! Please do it

**Comment by Ery4z** [comment]
“Please work for me freely as you should! This is the principle of open source no?”

**Comment by GaspardCulis** [comment]
> Can you add - custom adding voice from url?

I don't plan on adding new features to this project currently. You might want to implement this yourself (the code is open source), and if you manage to get it to work, I'll happily accept contributions to the code-base (open collaboration is one of the principles of open source).
