### ISSUE TITLE
Instalation

### ISSUE THREAD

**Issue by Lesnock** [GaspardCulis/elevenlabs-unleashed#12]
Hello!
I never wrote one line of python in my life, so I'm having some troubles...
I tried to install this package using the command specified in the README file:
```
pip install git+https://github.com/GaspardCulis/elevenlabs-unleashed.git
```

But it does not work:
```
python3 index.py                                                           
Traceback (most recent call last):
  File "/home/caio/dev/elevenlabs/index.py", line 1, in <module>
    from elevenlabs_unleashed.account import create_account
ModuleNotFoundError: No module named 'elevenlabs_unleashed'
```

Can someone help me with this?

Thanks!

**Comment by GaspardCulis** [comment]
Hi,

I can't really help you without more additional context. 

I guess the package installation failed and returned an error (weird thing is you would have reported that instead).

I see you're on Linux (*based*) and I know that you generally need to create a virtual environment to install pip packages. So I recommend you create a venv:

```bash
python3 -m venv venv
```

Activate it 

```bash
source venv/bin/activate
```

And then install the package and run your thing.

**Comment by ChaoticMonkey** [comment]
> Hi,
> 
> I can't really help you without more additional context.
> 
> I guess the package installation failed and returned an error (weird thing is you would have reported that instead).
> 
> I see you're on Linux (_based_) and I know that you generally need to create a virtual environment to install pip packages. So I recommend you create a venv:
> 
> ```shell
> python3 -m venv venv
> ```
> 
> Activate it
> 
> ```shell
> source venv/bin/activate
> ```
> 
> And then install the package and run your thing.

I did that but i get the error
```
(.venv) PS C:\Users\Monke\aiaudio> & c:/Users/Monke/aiaudio/.venv/Scripts/python.exe c:/Users/Monke/aiaudio/Index.py
Traceback (most recent call last):
  File "c:\Users\Monke\aiaudio\Index.py", line 1, in <module>
    from elevenlabs_unleashed.account import create_account
  File "C:\Users\Monke\aiaudio\.venv\Lib\site-packages\elevenlabs_unleashed\account.py", line 2, in <module>
    import names
ModuleNotFoundError: No module named 'names'
```

I made and activated venv, not sure what to do next

**Comment by GaspardCulis** [comment]
Yeah, maybe try 
```bash
pip install names
```

**Comment by DarthMaulone** [comment]
Hi,
I have the following error when creating the account: Exception has occurred: Exception Captcha not checked in time File 'C:\Users\****\*****\visual code\from gtts import gTTS.py', line 4, in <module> username, password, api_key = create_account() ^^^^^^^^^^^^^^^^ Exception: Captcha not checked in time"

**Comment by GaspardCulis** [comment]
> Hi,
> I have the following error when creating the account: Exception has occurred: Exception Captcha not checked in time File 'C:\Users\****\*****\visual code\from gtts import gTTS.py', line 4, in <module> username, password, api_key = create_account() ^^^^^^^^^^^^^^^^ Exception: Captcha not checked in time"
> 
> Thz

Hi, follow the procedure described in [this comment](https://github.com/GaspardCulis/elevenlabs-unleashed/issues/2#issuecomment-1708405321) to make the browser visible and describe me what's happening.

Does this exception happens every time ?

**Comment by GaspardCulis** [comment]
> Hi, I have the following error when creating the account: Exception has occurred: Exception Captcha not checked in time File 'C:\Users*_*****_*\visual code\from gtts import gTTS.py', line 4, in username, password, api_key = create_account() ^^^^^^^^^^^^^^^^ Exception: Captcha not checked in time"
> 
> Thz

Just tried myself, seems like the hCaptcha form was updated with new challenges, so you need to wait a bit and let the devs of the [hektCaptcha-extension](https://github.com/Wikidepia/hektCaptcha-extension) update their model, but it seems that the repo has recently been archived...

**Comment by DarthMaulone** [comment]
> > Hola, tengo el siguiente error al crear la cuenta: Se ha producido una excepción: Captcha de excepción no verificado a tiempo Archivo 'C:\Users* _*****_ *\visual code\from gtts import gTTS.py', línea 4, en nombre de usuario, contraseña, api_key = create_account() ^^^^^^^^^^^^^^^^ Excepción: Captcha no verificado a tiempo"
> > Thz
> 
> Lo acabo de probar yo mismo, parece que el formulario hCaptcha se actualizó con nuevos desafíos, por lo que debes esperar un poco y dejar que los desarrolladores de la [extensión hektCaptcha](https://github.com/Wikidepia/hektCaptcha-extension) actualicen su modelo, pero parece que el repositorio se archivó recientemente...

Thanks. I'll keep an eye out.
