### ISSUE TITLE
problem with usage code

### ISSUE THREAD

**Issue by komangulo** [GaspardCulis/elevenlabs-unleashed#14]
How do I use this code or where do I use it? it is not clear to me.
Do I have to create a .py file? a bash? modify a file in some directory?
 I would be grateful if you could guide me in this aspect please.
Thank you very much :D

**Usage
Create an account

from elevenlabs_unleashed.account import create_account

username, password, api_key = create_account()**

**Comment by GaspardCulis** [comment]
Hi, please refer to the [README](https://github.com/GaspardCulis/elevenlabs-unleashed#how-it-works). My code is just a fancy web scraper/bot that will automatically create 11Labs account , coupled with a fancy 11Labs API wrapper that will use these accounts to simulate an unlimited API
