### ISSUE TITLE
Issue creating account

### ISSUE THREAD

**Issue by InfiniteT8** [GaspardCulis/elevenlabs-unleashed#2]
I'm currently receiving an error that I didn't receive the email in time. 

Traceback (most recent call last):
  File "D:\Selenaz\Selenaz", line 3, in <module>
    username, password, api_key = create_account()
                                  ^^^^^^^^^^^^^^^^
  File "C:\Users\*****\AppData\Local\Programs\Python\Python311\Lib\site-packages\elevenlabs_unleashed\account.py", line 105, in create_account
    link = _get_confirmation_link(email)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\*****\AppData\Local\Programs\Python\Python311\Lib\site-packages\elevenlabs_unleashed\account.py", line 56, in _get_confirmation_link
    raise Exception("Email not received in time")
Exception: Email not received in time

could it be eleven lab's policy against using disposable emails?

**Comment by GaspardCulis** [comment]
Just tried, it still works, maybe you just had bad luck (already used mail, bad internet connection, 1secmail server issue). Does this always happens ?

**Comment by InfiniteT8** [comment]
After turning on debug, it seems to work for now. However, I did receive a warning for unusual activity. I'll try taking more time in between generating to see if it changes that.

**Comment by GaspardCulis** [comment]
Unusual activity warnings occur because you've used too many different api keys in a short amount of time, not because you've created too many accounts.

**Comment by InfiniteT8** [comment]
Could this be a result of me continuously testing the tool the night before? I figured there wouldn't be an issue if no API Keys were generated. It's only today that the script didn't fail. 

But upon reading through things, this is indeed highly experimental. At the moment, I'm trying to make use of tortoise-tts until I'm allowed to use the platform again.

**Comment by GaspardCulis** [comment]
Wait did you generated accounts all night ? Please avoid that, from my experience if you didn't called their API with different API keys in a short amount of time you shouldn't get the unusual activity warning. Making dozens of accounts shouldn't trigger this warning either.

**Comment by GaspardCulis** [comment]
Yeah their services are kinda overpriced

**Comment by Puffy4** [comment]
anyone have a gui i can use cause i also cant get it to work and i followed the instructions on terminal

**Comment by GaspardCulis** [comment]
I do not plan on making a GUI. But you can connect to the 11Labs website with the generated credentials, they have a TTS generation GUI.
