### ISSUE TITLE
Can't bypass ban

### ISSUE THREAD

**Issue by deonix37** [GaspardCulis/elevenlabs-unleashed#20]
Is private VPN the only solution?
```json
{
    "detail": {
        "status": "detected_unusual_activity",
        "message": "Unusual activity detected. Free Tier usage disabled. If you are using a proxy/VPN you might need to purchase a Paid Plan to not trigger our abuse detectors. Free Tier only works if users do not abuse it, for example by creating multiple free accounts. If we notice that many people try to abuse it, we will need to reconsider Free Tier altogether. \nPlease play fair and purchase any Paid Subscription to continue."
    }
}
```

**Comment by GaspardCulis** [comment]
If you are using a public VPN like proton or SouthVPN:

 > - Don't
 > - If you really want to then yes private VPN on a VPS

elif you are using it on your home connection (ie. from a private IP):

 > - Wait a few days, already had this issue, they'll remove you from their blacklist after some time
 > - Try not to use too many different accounts from the same IP too often, as that is what is causing the ban. That's why in my [UnleashedTTS class](https://github.com/GaspardCulis/elevenlabs-unleashed/blob/main/src/elevenlabs_unleashed/tts.py#L177) I always try to select the account with the most usage (but still having enough usage left).
