### ISSUE TITLE
Import errors due old version of Elevenlabs API

### ISSUE THREAD

**Issue by Dzendys** [GaspardCulis/elevenlabs-unleashed#23]
So I've come across your project and wanted to try it but ran into **imports problems**. I took a "deep" dive and investigate it on my own.

The imports inside **_tts.py_** are wrong due to changed **Elevenlabs API** - [here](https://github.com/elevenlabs/elevenlabs-python)

They made it so you don't have to use _get_api_key_ and _set_api_key_ and just use constructor.

**Your code:**
_if get_api_key() != account["api_key"]:
    print(
        "[ElevenLabs] Switching to account: "
        + account["username"]
        + " ("
        + str(account["character_count"])
        + "/"
        + str(account["character_limit"])
        + ")"
    )
set_api_key(account["api_key"])_

**Their code:**
_from elevenlabs.client import ElevenLabs

client = ElevenLabs(
  api_key="..." # Defaults to ELEVEN_API_KEY
)_

I'll try to work it out on my own, but I'm not that experienced with coding... let's see

**Comment by Dzendys** [comment]
Nope, too hard for me.. Man that's such a shame that one change in their API ruined this project

**Comment by GaspardCulis** [comment]
Thx for the issue! I didn't know they updated their SDK
