### ISSUE TITLE
I cant seem to make it work

### ISSUE THREAD

**Issue by Puffy4** [GaspardCulis/elevenlabs-unleashed#3]
I cant seem to make it work any chance i can get a file i can run on mac cause i pasted the code on terminal and thats what i get
" pip.
  full command: git clone --filter=blob:none https://github.com/GasparldCulis/elevenlabs-unleashed.git /private/var/folders/zd/6v32k96n0rd01gdjd1f_n9fm0000gn/T/pip-req-build-gh50fp4d
  cwd: [inherit]
error: subprocess-exited-with-error

× git clone --filter=blob:none https://github.com/GasparldCulis/elevenlabs-unleashed.git /private/var/folders/zd/6v32k96n0rd01gdjd1f_n9fm0000gn/T/pip-req-build-gh50fp4d did not run successfully.
│ exit code: 128
╰─> See above for output.

**Comment by Puffy4** [comment]
yes and I did Pip3 install git+Https://github.com/GaspardCulis/elevenlabs-unleashed.git
thats what i get now mustafaelbaf@Mustafas-MacBook-Pro ~ % from elevenlabs_unleashed.account import create_account

username, password, api_key = create_account()
function>

**Comment by GaspardCulis** [comment]
Are you a LLM ? I can't see any errors here, did you checked the username and password variables after creating the account ?

Example:
```python
from elevenlabs_unleashed.account import create_account

username, password, api_key = create_account()

print(f"Username: {username} | password: {password} | API key: {api_key}")
```

**Comment by Puffy4** [comment]
i Copied and pasted this " Create an account

from elevenlabs_unleashed.account import create_account

username, password, api_key = create_account()" 
AND this is what im getting " function>"

**Comment by Puffy4** [comment]
what do i do after this step " Not a very explicit error trace. Did you run this command to install ?

pip install git+https://github.com/GaspardCulis/elevenlabs-unleashed.git"

**Comment by GaspardCulis** [comment]
Did you executed this python code in a python shell ?

You first have to install the library:
```bash
# In your terminal
pip install git+https://github.com/GaspardCulis/elevenlabs-unleashed.git"
```

Then run `python` in your terminal to get python shell, and then you paste the python code.
```python
from elevenlabs_unleashed.account import create_account

username, password, api_key = create_account()

print(f"Username: {username} | password: {password} | API key: {api_key}")
```

 I suggest you first watch some Python YT tutorials you look like a beginner

**Comment by Puffy4** [comment]
ok thanks for taking the time to answer i will try and do it again and see what happens
this is what im getting
mustafaelbaf@Mustafas-MacBook-Pro ~ % python3
Python 3.11.1 (v3.11.1:a7a450f84a, Dec  6 2022, 15:24:06) [Clang 13.0.0 (clang-1300.0.29.30)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from elevenlabs_unleashed.account import create_account
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'elevenlabs_unleashed'
>>> 
>>> username, password, api_key = create_account()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'create_account' is not defined
>>> 
>>> print(f"Username: {username} | password: {password} | API key: {api_key}")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'username' is not defined

**Comment by Puffy4** [comment]
so basically i followed your instructions on terminal and then i typed 
Python3
then i typed  from elevenlabs_unleashed.account import create_account

username, password, api_key = create_account()


i am getting this error
>>> from elevenlabs_unleashed.account import create_account
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'elevenlabs_unleashed'
>>> 
>>> username, password, api_key = create_account()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'create_account' is not defined

**Comment by GaspardCulis** [comment]
Well, seems like the library isn't installed with the previously mentionned `pip` command.

**Comment by Puffy4** [comment]
but i did pip3 install git+https://github.com/GaspardCulis/elevenlabs-unleashed.git

**Comment by Puffy4** [comment]
after using python3 >> from elevenlabs_unleashed.methods import create_account
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'elevenlabs_unleashed.methods' I get this

**Comment by GaspardCulis** [comment]
Okay, this the issue certainly isn't coming from my library code. Are you on Linux (if yes then what distro) ? Learn about python virtualenv first. And then when you've got a better python understanding. Try to install `elevenlabs_unleashed` in a virtualenv this will make it easier to debug.
