### ISSUE TITLE
raise Exception("Email not received in time")

### ISSUE THREAD

**Issue by anuj-paude1** [GaspardCulis/elevenlabs-unleashed#4]
raise Exception("Email not received in time")

**Comment by anuj-paude1** [comment]
Current domain is flagged as a disposable domain. 
Changing MAIL_DOMAIN = "vjuum.com" worked.

**Comment by GaspardCulis** [comment]
Thanks forr finding a new domain, changed the previous one with your in commit ad5553d14b00b2ffbccb95c817d6565e879b8eed

**Comment by anuj-paude1** [comment]
It would be better if you just shuffle between these domains , ["1secmail.com","1secmail.org","1secmail.net","ezztt.com","vjuum.com","laafd.com","txcct.com"]

**Comment by GaspardCulis** [comment]
True, I just gotta find all valid domains and when Exception I switch to another domain

**Comment by db-alakaboom** [comment]
Busted for me :(

**Comment by GaspardCulis** [comment]
Seems like elevenlabs changed account creation policy:
![image](https://github.com/GaspardCulis/elevenlabs-unleashed/assets/79080828/3110f6ac-056f-4fde-9be1-56889525e655)
Tested for some very random mails using the `vjuum.com` domain, I always get the "Email already in use" message. (no way someone used the mail `thisisarandomamil69425678973@vjuum.com`, but says its used)

I think it's just a replacement message for the old "Don't use disposable emails" message. Try find another domain maybe
