### ISSUE TITLE
Captcha added, but solve it!

### ISSUE THREAD

**Issue by CroSSer23** [GaspardCulis/elevenlabs-unleashed#6]
Hi. Your code is good, add captcha bypass, I even know how!
https://github.com/Wikidepia/hektCaptcha-extension
There is an extension.
Load it together with chromedriver and check if the captcha is passed. 
If you want, we can team up. 
Write to me in TG @crosser23.

**Comment by GaspardCulis** [comment]
Okay great didn't knew Captcha were so easy to bypass, I mean no need for TG, just ~~do the job for me~~ submit a PR and I'll merge it.
