### ISSUE TITLE
Api and account - Eleven Lans

### ISSUE THREAD

**Issue by MattiaMc** [GaspardCulis/elevenlabs-unleashed#8]
inserting this in console 

```
from elevenlabs_unleashed.account import create_account

username, password, api_key = create_account() “
```

starts the automated browser procedure (chrome browser), opens the home page and creates the username and password automatically but then two things happen: either the automatic capcha procedure doesn't have time to resolve itself (error in python console ) or the browser closes. in the rare cases in which everything goes well it lets me access the Eleven page but then asks me to add the credentials by hand. Am I doing something wrong? I also don't see the APIs he created. ps: chromedriver (v.117) is ok. Thank you!

“

**Comment by GaspardCulis** [comment]
Yeah I see that the Captcha procedure has been updated, and the anti captcha extension can't handle it anymore.

**Comment by GaspardCulis** [comment]
Tested the account creation procedure yesterday, seems to work again !
